# Generated by Django 4.1.4 on 2022-12-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento'},
        ),
        migrations.AlterField(
            model_name='eventos',
            name='meals',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
