# Generated by Django 4.1.4 on 2022-12-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventos_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='meals',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
