# Generated by Django 4.1.4 on 2022-12-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventos_meals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='date',
            new_name='registrationDate',
        ),
    ]
