# Generated by Django 4.1.4 on 2022-12-12 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventos_registrationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tipo', models.DecimalField(max_digits=3, decimal_places=0)),
                ('register', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='eventos',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.salas'),
        ),
    ]
