# Generated by Django 4.1.4 on 2022-12-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_salas_alter_eventos_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='register',
        ),
    ]
