# Generated by Django 4.1.4 on 2022-12-12 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_salas_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo',
            },
        ),
        migrations.AlterModelOptions(
            name='salas',
            options={'verbose_name': 'Sala'},
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='events.tipos'),
            preserve_default=False,
        ),
    ]
