# Generated by Django 4.1.4 on 2022-12-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventos_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='matter',
            new_name='name',
        ),
    ]
