# Generated by Django 4.1.3 on 2022-12-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_matter_eventos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='timeEnd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='timeStart',
            field=models.TimeField(),
        ),
    ]
