# Generated by Django 4.1.3 on 2022-12-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventos_timeend_alter_eventos_timestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='tipo',
            field=models.CharField(choices=[('1', 'Aula'), ('2', 'Evento')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Tipos',
        ),
    ]
