# Generated by Django 4.1.4 on 2023-01-11 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_eventos_tipo_delete_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.salas', verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='meals',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Refeições'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Disciplina ou Tema:'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='registrationDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='timeEnd',
            field=models.TimeField(verbose_name='Hora final'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='timeStart',
            field=models.TimeField(verbose_name='Hora inicial'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tipo',
            field=models.CharField(max_length=12),
        ),
    ]
