from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name = 'home'),
    path('all/', views.allEvents, name = 'allEvents'),
    path('today/', views.today, name = 'today'),
    path('week/', views.week, name = 'week'),
    path('month/', views.month, name = 'month'),
    path('year/', views.year, name = 'year'),
    path('weekClassrooms/', views.weekClassrooms, name = 'weekClassrooms'),
    path('monthClassrooms/', views.monthClassrooms, name = 'monthClassrooms'),
    path('yearClassrooms/', views.yearClassrooms, name = 'yearClassrooms'),
     path('todayClassrooms/', views.classroomsToday, name = 'todayClassrooms'),
    path('todayEvents/', views.eventsToday, name = 'todayEvents'),
    path('monthEvents/', views.monthEvents, name = 'monthEvents'),
    path('yearEvents/', views.yearEvents, name = 'yearEvents'),
    path('weekEvents/', views.weekEvents, name = 'weekEvents'),
    path('weekUser/', views.weekUser, name = 'weekUser'),
    path('monthUser/', views.monthUser, name = 'monthUser'),
    path('yearUser/', views.yearUser, name = 'yearUser'),
    path('events/', views.events, name = 'events'),
    path('classrooms/', views.classrooms, name = 'classrooms'),
    path('eventsUser/', views.eventsUser, name = 'eventsUser'),
    path('classroomsUser/', views.classroomsUser, name = 'classroomsUser'),
    path('weekUserEvents/', views.weekUserEvents, name = 'weekUserEvents'),
    path('yearUserEvents/', views.yearUserEvents, name = 'yearUserEvents'),
    path('monthUserEvents/', views.monthUserEvents, name = 'monthUserEvents'),
    path('yearUserClassrooms/', views.yearUserClassrooms, name = 'yearUserClassrooms'),
    path('monthUserClassrooms/', views.monthUserClassrooms, name = 'monthUserClassrooms'),
    path('weekUserClassrooms/', views.weekUserClassrooms, name = 'weekUserClassrooms'),
    path('addEvent/', views.addEvent, name = 'addEvent'),
    path('addClassroom/', views.addClassroom, name = 'addClassroom'),
    path('registerEvent/', views.registerEvent, name= 'registerEvent'),
    path('edit/<int:id>', views.update, name='edit'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('about/', views.about, name='about'),

]